languageCode = "fr-fr"
title = "Site de la Fun"
theme = "hugo-flex"

[menu]
  [[menu.main]]
    identifier = "LaFun"
    name = "La Fun"
    url = "/Lafun"
    weight = 1
  [[menu.main]]
    identifier = "LaFun-Association"
    name = "L'association"
    url = "/LaFun/association"
    parent = "LaFun"
    weight = 1
  [[menu.main]]
    identifier = "LaFun-adherer"
    name = "Adherer"
    url = "/LaFun/adherer"
    parent = "LaFun"
    weight = 2
  [[menu.main]]
    identifier = "LaFun-avecqui"
    name = "Avec qui"
    url = "/LaFun/avecqui"
    parent = "LaFun"
    weight = 3
  [[menu.main]]
    identifier = "actualites"
    name = "Actualités"
    url = "/actualites"
    weight = 2
  [[menu.main]]
    identifier = "agenda"
    name = "Agenda"
    url = "/Agenda"
    weight = 3
  [[menu.main]]
    identifier = "Activites"
    name = "Activités"
    url = "/activites"
    weight = 4
  [[menu.main]]
    identifier = "Activites-funlab"
    name = "Le Funlab"
    url = "/Activites/funlab"
    parent = "Activites"
    weight = 1
  [[menu.main]]
    identifier = "Activites-education"
    name = "Education"
    url = "/Activites/education"
    parent = "Activites"
    weight = 2
  [[menu.main]]
    identifier = "Activites-cooperation"
    name = "Cooperation"
    url = "/Activites/cooperation"
    parent = "Activites"
    weight = 3
  [[menu.main]]
    identifier = "Activites-programmation"
    name = "Programmation"
    url = "/Activites/programmation"
    parent = "Activites"
    weight = 4
  [[menu.main]]
    identifier = "Activites-accompagnement"
    name = "Accompagnement"
    url = "/Activites/accompagnement"
    parent = "Activites"
    weight = 5
  [[menu.main]]
    identifier = "infopratique"
    name = "Infos pratiques"
    url = "/infos"
    weight = 5
  [[menu.main]]
    identifier = "Ressources"
    name = "Ressources"
    url = "/ressources"
    weight = 6
  [[menu.main]]
    identifier = "Ressources-wiki"
    name = "Wiki La Fun"
    url = "https://wiki.lafun.fr/"
    parent = "Ressources"
    weight = 1
  [[menu.main]]
    identifier = "Ressources-cracn"
    name = "CRACN"
    url = "https://cracn.fr/"
    parent = "Ressources"
    weight = 2
  [[menu.main]]
    identifier = "Ressources-peertube"
    name = "Peertube"
    url = "https://tube.lafun.fr/"
    parent = "Ressources"
    weight = 3
  [[menu.main]]
    identifier = "Ressources-futuretic"
    name = "FuturEtic"
    url = "https://futuretic.fr/"
    parent = "Ressources"
    weight = 1
  [[menu.main]]
    identifier = "Ressources-preciouskitchen"
    name = "Precious Kitchen"
    url = "https://precious.kitchen/"
    parent = "Ressources"
    weight = 1
  [[menu.main]]
    identifier = "connexion"
    name = "Connexion"
    url = "/"
    weight =7

[taxonomies]
  tag = "tags"

[permalinks]
  Actualites = "/:year/:month/:title/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100
