name: Build and Deploy

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  build:
    name: Build and Deploy
    runs-on: self-hosted
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
      env:
        runner: self-hosted

    - name: Build
      run: hugo --minify
      
    - name: Debug
      run: pwd && ls -la && ls -la / && ls -la /tmp

    - name: Clean
#      run: rm -rf /hugo/*
      run: ls -la /hugo

    - name: Copy
#      run: rsync -av --progress sourcefolder /destinationfolder --exclude thefoldertoexclude
      run: cp -r ./* /hugo/
